- name: Create a bucket
  amazon.aws.s3_bucket:
    name: "{{ s3_bucket_name }}"
    state: present
 
- name: Create Folder in S3 Bucket
  aws_s3:
    bucket: "{{ s3_bucket_name }}"
    object: "{{ s3_folder_name }}"
    mode: create
 
- name: Enabling versioning for S3 bucket
  amazon.aws.s3_bucket:
    name: "{{ s3_bucket_name }}"
    state: present
    public_access:
      block_public_acls: true
      ignore_public_acls: true
      block_public_policy: true
      restrict_public_buckets: true
    versioning: true
    region: "{{ aws_region }}"
 
- name: Enabling logging for S3 bucket
  community.aws.s3_logging:
    name: "{{ s3_bucket_name }}"
    target_bucket: "{{ s3_bucket_name }}"
    target_prefix: "{{ s3_logging_prefix }}"
    state: present
    region: "{{ aws_region }}"
 
- name: Configuring a lifecycle policy rule on bucket to expire (delete) items with a prefix of /logs/ after 30 days
  amazon.aws.s3_lifecycle:
    name: "{{ s3_bucket_name }}"
    expiration_days: "{{ s3_lifecycle_expiration_days }}"
    prefix: "{{ s3_lifecycle_prefix }}"
    status: enabled
    state: present
    region: "{{ aws_region }}"
