- name: Create Glue crawler
  community.aws.glue_crawler:
    name: "{{ glue_crawler_name }}"
    database_name: "{{ glue_database_name }}"
    role: "{{ glue_role_arn }}"
    schema_change_policy:
      delete_behavior: "{{ glue_delete_behavior }}"
      update_behavior: "{{ glue_update_behavior }}"
    recrawl_policy:
      recrawl_behavior: "{{ glue_recrawl_behavior }}"
    targets:
      S3Targets: "{{ glue_s3_targets | map('combine', {'ConnectionName': glue_connection_name, 'Exclusions': glue_s3_exclusions}) | list }}"
    state: "{{ glue_state }}"
    region: "{{ aws_region }}"
