- name: Update Lambda function configurations
  amazon.aws.lambda:
    name: "{{ lambda_function_name }}"
    state: present
    role: "{{ lambda_role_arn }}"
    region: "{{ aws_region }}"
    runtime: "{{ lambda_runtime }}"
    description: "{{ lambda_description }}"
    timeout: "{{ lambda_timeout }}"
    memory_size: "{{ lambda_memory_size }}"
    handler: "{{ lambda_handler }}"
    environment_variables: "{{ lambda_environment_variables }}"
    tags: "{{ lambda_tags }}"
    zip_file: "{{ lambda_zip_file }}"
